baseURL: https://matteosonoio.it/
languageCode: en-us
title: Matteo Contrini
theme: PaperMod

defaultContentLanguage: en

languages:
  en:
    languageName: English
    description: I'm Matteo, a software engineer from Italy.
  it:
    languageName: Italiano
    description: Sono Matteo, uno sviluppatore software.

menu:
  main:
  - identifier: blog
    name: Blog
    url: /blog/

params:
  env: production
  ShowReadingTime: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  DateFormat: 2006-01-02
  comments: true

  profileMode:
    enabled: true
    subtitle: Software engineer. Building digital products.
    buttons:
    - name: Blog 🇮🇹
      url: "/it/blog/"
    - name: Blog 🇬🇧
      url: "/blog/"
    imageUrl: /glitch.jpg

  socialIcons:
    - name: Twitter
      url: https://twitter.com/matteosonoioo
    - name: GitHub
      url: https://github.com/matteocontrini
    - name: LinkedIn
      url: https://www.linkedin.com/in/matteo-contrini/
    - name: Telegram
      url: https://t.me/notedimatteo
    - name: Email
      url: mailto:matteo@contrini.it

permalinks:
  posts: /:slug/

markup:
  goldmark:
    renderer:
      unsafe: true
