baseURL: https://matteosonoio.it/
languageCode: en-us
title: Matteo Contrini
theme: PaperMod

defaultContentLanguage: en

languages:
  en:
    languageName: English
    description: I'm Matteo, a software engineer and cloud infrastructure admininistrator from Italy. This is my personal blog.
    homeInfoParams:
      title: Hi there 👋
      content: I'm Matteo and I'm from Italy. I recently graduated in Computer Science at the University of Trento. I write code (mostly backend) and I have experience in cloud infrastructure and video streaming technologies.<br><br>This is my personal blog. You can find more about me if you switch the language to [🇮🇹 Italian](/it/).
    menu:
      main:
        - identifier: archive
          name: Archive
          url: /archive/
  it:
    languageName: Italiano
    description: Sono Matteo, uno sviluppatore software e amministratore di infrastruttura cloud. Questo è il mio blog personale.
    homeInfoParams:
      title: Ciao 👋
      content: Mi chiamo Matteo e sono laureato in informatica all'Università di Trento. Mi occupo quotidianamente di sviluppo software e gestione di infrastrutture cloud, ma ho anche esperienza in tecnologie di streaming video.<br><br>Alcune cose che faccio:<br>- Scrivo la newsletter settimanale [Storie di bit](https://storiedibit.it/) su Internet, AI e digitale<br>- Ho co-fondato e gestisco [TrackBot](https://trackbot.eu) e [TrackBot Pro](https://trackbot.pro), servizi per il tracking delle spedizioni<br>- Collaboro con una startup edtech / AI<br>- In passato ho fondato e sono stato amministratore di [FibraClick](https://fibra.click)<br>- Mi trovi anche nel mio [canale Telegram](https://t.me/notedimatteo)<br><br>Questo è il mio blog personale, dove scrivo sia in [🇺🇸 inglese](/) che in [🇮🇹 italiano](/it/).
    menu:
      main:
        - identifier: archive
          name: Archivio
          url: /archive/

params:
  env: production
  ShowReadingTime: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  DateFormat: 2006-01-02
  comments: true

  socialIcons:
    - name: Twitter
      url: https://twitter.com/matteosonoioo
    - name: GitHub
      url: https://github.com/matteocontrini
    - name: LinkedIn
      url: https://www.linkedin.com/in/matteo-contrini/
    - name: Telegram
      url: https://t.me/notedimatteo

permalinks:
  posts: /:slug/

markup:
  goldmark:
    renderer:
      unsafe: true
