baseURL: https://matteosonoio.it/
title: Matteo Contrini
theme: PaperMod

defaultContentLanguage: en

languages:
  en:
    contentDir: content/en
    label: English
    locale: en-US
    params:
      description: I'm Matteo, a software engineer from Italy.
      profileMode:
        subtitle: I'm a software engineer and independent founder.<br>I build digital products and write about software and digital.
  it:
    contentDir: content/it
    label: Italiano
    locale: it-IT
    params:
      description: Sono Matteo, uno sviluppatore software.
      profileMode:
        subtitle: Sono un ingegnere del software e founder indipendente.<br>Costruisco prodotti digitali e qui scrivo di software e digitale.

menu:
  main:
  - identifier: blog
    name: Blog
    url: /blog/

params:
  env: production
  ShowReadingTime: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  DateFormat: 2006-01-02
  comments: true

  profileMode:
    enabled: true
    buttons:
    - name: 🇮🇹 Blog
      url: "/it/blog/"
    - name: 🇮🇹 Note
      url: "https://notedimatteo.it"
    - name: 🇬🇧 Blog
      url: "/blog/"
    imageUrl: /glitch.jpg

  socialIcons:
    - name: Twitter
      url: https://twitter.com/matteosonoioo
    - name: GitHub
      url: https://github.com/matteocontrini
    - name: LinkedIn
      url: https://www.linkedin.com/in/matteo-contrini/
    - name: Email
      url: mailto:matteo@contrini.it

permalinks:
  posts: /:slug/

markup:
  goldmark:
    renderer:
      unsafe: true
