[build]
command = "hugo"
publish = "public"

[build.environment]
HUGO_VERSION = "0.89.1"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"
